---
title: Gentle Girth and Womens Health
timezone: MST
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
headline: The Miracle of Birth from the Comfort of Home
subheadline: also offering womens heath care.
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description. '
baseurl: ''
url: http://gentlebirthandwomenshealth.siteleaf.net
permalink: pretty
facebook_username: example
authors:
  karla:
    name: Karla Jo Bennett - Certified Nurse Midwife
markdown: kramdown
gems:
- jekyll-feed
include:
- _pages
exclude:
- readme.md
- Gemfile
- Gemfile.lock
