---
title: Gentle Birth
subtitle: and women's health
timezone: America/Denver
collections:
  posts:
    title: Posts
    output: true
  testimonials:
    title: Testimonials
    output: true
  uploads:
    title: Uploads
    output: true
headline: The Miracle of Birth
subheadline: from the Comfort of Home
email: "UtahGentleBirthMidwife@gmail.com"
description: At Gentle Birth and Women's Health we offer natural safe pregnancy and
  home birth services, and respectful holistic women's health care. We provide one-on-one
  attention from an experienced Certified Nurse Midwife, committed to protecting your
  birth and your health.
baseurl: /gentlebirth/
url: http://justgage.github.io/gentlebirth/
permalink: pretty
facebook_username: gentlebirthandwomenshealth
authors:
  karla:
    name: Karla Jo Bennett - Certified Nurse Midwife
markdown: kramdown
include:
- _pages
exclude:
- readme.md
- Gemfile
- Gemfile.lock
